### ISSUE TITLE
Implement helper class for local storage

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/kaskadi-scripts#2]
**Is your feature request related to a problem? Please describe.**
We often communicate with the browser local storage in the Kaskadi project. Most of those communications include setting/updating/deleting multiple entries at once which generates a lot of redundant code (see [here](https://github.com/kaskadi/kaskadi-scripts/blob/dc7b48e8febb858a27a91106a81d6dcaf57c0754/kaskadi-scripts/kaskadi-auth-helper.js#L69-L78) for example).

**Describe the solution you'd like**
I'd like to have a new helper that offers the following API:
- `.get: String[] -> Object`: method that takes as input an array of strings (_keys_) and returns an object where the keys are the ones provided as input and the associated values are the one found in local storage for each given key.
- `.set: Object -> any`: method that takes as input an object and store in local storage all the key-value pairs found in this object. It can return either a confirmation message, an empty object or a boolean to indicate the status of the operation (`true` <=> success, `false` <=> failure)
- `.remove: String[] -> any`: method that takes as input an array of strings (_keys_) and remove those keys from the local storage. It can return either a confirmation message, an empty object or a boolean to indicate the status of the operation (`true` <=> success, `false` <=> failure)

**Additional context**
Other helpers are created using classes. Follow the same logic.

**Comment by beatadetkova** [comment]
I can help there.
